"""
Django settings for home_services project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
      # 'two_factor.plugins.phonenumber',
]

# django_otp: This is the main engine of OTP system.It handles:OTP creation,OTP verification,OTP storage,OTP validation logic.
# This app gives Django ability to use One Time Passwords. Example: When user logs in:Step 1: username/password correct,
# Step 2: OTP required, Step 3: verify OTP

# django_otp.plugins.otp_totp: TOTP = Time-based OTP. OTP changes every 30–60 seconds.
# Example apps:Google Authenticator,Microsoft Authenticator.
# How it works:Step 1:Server and phone share a secret key , Step 2: Phone generates code like: 123456 (changes every 30 sec),
# Step 3:Server generates same code using time, Step 4: If match → login success. TOTP = OTP generated using time + secret key

# django_otp.plugins.otp_static: This is backup OTP system. Pre-generated OTP codes stored in database. 
# When user enables 2FA:System gives: Backup codes:A1B2C3,D4E5F6,G7H8I9. Use case:If phone is lost: user uses backup code

# two_factor: Complete ready-made 2FA login system for Django. This is the main framework that connects everything
# It combines:login system, OTP system, QR code setup,authentication flow,UI pages

EXTERNAL_APPS = [
    'apps.users',
    'apps.services',
    'rest_framework',
    'rest_framework_simplejwt',
]

INSTALLED_APPS += EXTERNAL_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# django_otp.middleware.OTPMiddleware:It is a Django middleware that enforces two-factor authentication by checking 
# whether the user has completed OTP verification before granting full access.This middleware is NOT just a checker.It is:A system 
# that controls whether a user has completed second-factor authentication (OTP) or not. 
# 1. User enters password
#         ↓
# 2. AuthenticationMiddleware → sets user
#         ↓
# 3. OTPMiddleware → checks 2FA status
#         ↓
# 4. If OTP not verified → block/redirect
#         ↓
# 5. If verified → access granted

ROOT_URLCONF = 'home_services.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_services.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# [Django starts request
#         ↓
# ORM (models.py)
#         ↓
# DATABASE ENGINE (PostgreSQL driver)
#         ↓
# Connect to HOST = db
#         ↓
# PORT = 5432
#         ↓
# Login using USER + PASSWORD
#         ↓
# Access DATABASE = tasks_db
#         ↓
# Run SQL queries
#         ↓
# Return data to Djang]



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.User'
# AUTH_USER_MODEL = 'users.User':Django should use MY custom User model instead of default built-in User model.
# users.User = User model inside users app --> AUTH_USER_MODEL = 'users.User' → tells Django to use custom user model
# → replaces default auth.User,→ enables custom fields like role,→ used everywhere in authentication system.
# AUTH_USER_MODEL = users.User
#         ↓
# Django auth system loads custom User
#         ↓
# Login uses this model
#         ↓
# request.user = users.User object
#         ↓
# permissions check role field

# 'DEFAULT_AUTHENTICATION_CLASSES':How should Django identify the user making a request?
# JWTAuthentication does:Every request checks:Authorization: Bearer <token>. Then it:✔ Validates token,✔ Extracts user info,✔ Sets request.user.
# Client sends request + token
#         ↓
# JWTAuthentication reads token
#         ↓
# Validates signature
#         ↓
# Finds user
#         ↓
# Sets request.user

# DEFAULT_PERMISSION_CLASSES:What is user allowed to do by default? 
# IsAuthenticated means:Only logged-in users can access APIs.
# Request comes in
#         ↓
# Check authentication first
#         ↓
# If user logged in → allow
# If not logged in → block

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

AUTHENTICATION_BACKENDS = (
    # 'two_factor.backends.TwoFactorAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)
#AUTHENTICATION_BACKENDS:→ system that verifies login credentials,→ ModelBackend = default username/password system,→ used during login before JWT creation
LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/account/login/'
TWO_FACTOR_REMEMBER_COOKIE_AGE = None

# These are used mainly in Django session-based authentication (not JWT APIs).
# LOGIN_URL = '/account/login/':If a user is NOT logged in and tries to access a protected page, redirect them here.where unauthenticated users are sent
# LOGIN_REDIRECT_URL = '/admin/':After successful login, send user to this page.where user goes after login
# LOGOUT_REDIRECT_URL = '/account/login/':After logout, send user to this page.where user goes after logout